desafio_final/desafio_final/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from portal import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',views.home ),
    path('admin/', admin.site.urls),
    path("portal/" , include("portal.urls")),
    path("mensajes/",include("mensajes.urls"))
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

desafio_final/portal/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("",views.inicio,name="home"),
    path("inicio",views.inicio,name="inicio"),
    path("politica", views.politica ,name="politica"),
    path("economia", views.economia ,name="economia"),
    path("sociedad", views.sociedad ,name="sociedad"),
    path("deportes", views.deportes ,name="deportes"),
    path("nueva_publicacion", views.nueva_publicacion ,name="nueva_publicacion"),
    path("resultados", views.resultados ,name="resultados"),
    path("lectura", views.lectura ,name="lectura"),
    #path("formulario_periodistxs" , views.formulario_periodistxs, name="formulario_periodistxs"),
    #path("formulario_lectorxs" , views.formulario_lectorxs, name="formulario_lectorxs"),
    path("lectura/<int:id>", views.lectura ,name="lectura"),
    path("borrar_publicacion/<int:id_noticia>",views.borrar_publicacion,name="borrar_publicacion"),
    path("editar_publicacion/<int:id_noticia>",views.editar_publicacion,name="editar_publicacion"),
    path("editar_publicacion",views.editar_publicacion,name="editar_publicacion"),
    path("login",views.login_request,name="Login"),
    path("register",views.register,name="register"),
    path("logout",LogoutView.as_view(template_name="logout.html"),name="logout"),
    path("editar_perfil",views.editar_perfil,name="editar_perfil"),
    path("home",views.home,name="home"),
    path("mis_publicaciones",views.mis_publicaciones,name="mis_publicaciones"),
    path("cambiar_avatar",views.cambiar_avatar,name="cambiar_avatar"),
    path("about",views.about,name="about")
    
]

desafio_final/portal/models.py
from distutils.command.upload import upload
from django.db import models
from django.forms import CharField, DateField, EmailField, IntegerField
from django.contrib.auth.models import User

# Create your models here.

#Modelo de posteo de noticias
class Noticia(models.Model):
    seccion = models.CharField(max_length=50)
    titulo = models.CharField(max_length=140)
    bajada = models.CharField(max_length=10000)
    cuerpo = models.CharField(max_length=30000)
    fecha = models.DateTimeField()
    img = models.ImageField(upload_to='img/', null=True ,blank=True )
    nombre_user = models.CharField(max_length=50)
    id_user = models.IntegerField()
    publicado = models.BooleanField()
    home = models.BooleanField()

    def __str__(self):
            return f"ID: {self.id} | Sección: {self.seccion} - Título: {self.titulo}"


class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True ,blank=True )

    def __str__(self) -> str:
          return f"ID: {self.id}, User: {self.user}"
          
class Imagen_post(models.Model):
    id_post = models.IntegerField()
    imagen = models.ImageField(upload_to='img', null=True ,blank=True )

    

class Lectorxs(models.Model):
    nombre_lectorxs = models.CharField(max_length=50)
    pass_lectorxs = models.CharField(max_length=50)
    email_lectorxs = models.EmailField()
    dni_lectorxs = models.IntegerField()
    nro_tarjeta_crédito = models.IntegerField()
    modo_suscripcion = models.CharField(max_length=30)


    def __str__(self):
            return f"ID: {self.id} Nombre: {self.nombre_lectorxs}, E-mail: {self.email_lectorxs}"

class Periodistxs(models.Model):
    nombre_periodistxs = models.CharField(max_length=50)
    sigla_periodistxs = models.CharField(max_length=10)
    pass_periodistxs = models.CharField(max_length=50)
    email_periodistxs = models.EmailField()
    dni_periodistxs = models.IntegerField()

    def __str__(self):
            return f"ID: {self.id} - Nombre: {self.nombre_periodistxs}, E-mail: {self.email_periodistxs}"

desafio_final/portal/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class Nueva_noticia(forms.Form):
    seccion = forms.CharField(max_length=50)
    titulo = forms.CharField(max_length=140)
    bajada = forms.CharField(max_length=10000)
    cuerpo = forms.CharField(max_length=30000)
    #fecha = forms.DateField()
    img = forms.ImageField()
    nombre_user = forms.CharField(max_length=50)
    id_user = forms.IntegerField()
    publicado = forms.IntegerField()
    home = forms.IntegerField()

class User_Edit_Form(UserCreationForm):
    email = forms.EmailField(label="Modificar")
    password1: forms.Field(label="Contraseña", widget=forms.PasswordInput)
    password2: forms.Field(label="Repetir la contraseña",widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['email','password1','password2']
        help_texto = {k:"" for k in fields}

class Nuevxs_Lectorxs(forms.Form):
    nombre_lectorxs = forms.CharField(max_length=50)
    pass_lectorxs = forms.CharField(max_length=50)
    email_lectorxs = forms.EmailField()
    dni_lectorxs = forms.IntegerField()
    nro_tarjeta_crédito = forms.IntegerField()
    modo_suscripcion = forms.CharField(max_length=30)

    
class Nuevxs_Periodistxs(forms.Form):
    nombre_periodistxs = forms.CharField(max_length=50)
    sigla_periodistxs = forms.CharField(max_length=10)
    pass_periodistxs = forms.CharField(max_length=50)
    email_periodistxs = forms.EmailField()
    dni_periodistxs = forms.IntegerField()

desafio_final/portal/views.py
from ast import Pass
from datetime import datetime
from time import timezone
from turtle import home
from django.shortcuts import render
from portal.forms import Nueva_noticia, User_Edit_Form
from portal.models import Noticia, Avatar
from django.template import loader
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login,authenticate, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
# Create your views here.

#Función que carga en un diccionario la DB para mostrar en diferentes páginas del sitio
#Se carga la lista de noticias completa, la lista de noticias que va a la marquesina de "Últimos Títulos" y la lista que va al carousel
#y los datos y avatar de quien se haya loggeado, la llamo para enviar el diccionario generado en cada return
def dicc(request):
    noticias= Noticia.objects.all()
    noticias_titulos=noticias[::-1]
    noticias_home=[]
    for n in noticias_titulos:
        if n.home == 1:
            noticias_home.append(n)
    n1 = noticias_home[0]
    n2 = noticias_home[1]
    n3 = noticias_home[2]
    avatares = Avatar.objects.filter(user=request.user.id)
    if avatares.exists():
        return ({"noticias":noticias[::-1], "noticias_titulos":noticias_titulos[0:5],"noticia1":n1,"noticia2":n2,"noticia3":n3,"url":avatares[0].imagen.url})
    else:
        return ({"noticias":noticias[::-1], "noticias_titulos":noticias_titulos[0:5],"noticia1":n1,"noticia2":n2,"noticia3":n3,"url":"/media/avatares/basico.png"})

#Página de bienvenida
def home(request):
    return render(request, "home.html",dicc(request))

#Página de inicio
def inicio(request,*kwargs):
    data=dicc(request) 
    if kwargs:
        data.update(kwargs[0])
    return render(request, "index.html",data)
    
@login_required
#Muestro las publicaciones hechas por quien se haya loggeado
def mis_publicaciones(request):
    mis_noticias=Noticia.objects.filter(id_user__exact = request.user.id)
    data=(dicc(request))
    data.update({"mis_noticias":mis_noticias[::-1]})
    return render(request, "mis_publicaciones.html",data)


#Secciones
@login_required
def politica(request):
    return render(request, "1politica.html",dicc(request))
    
    
@login_required
def economia(request):
    return render(request, "2economia.html",dicc(request))

@login_required
def sociedad(request):
    return render(request, "3sociedad.html",dicc(request))

@login_required
def deportes(request):
    return render(request, "4deportes.html",dicc(request))

# Formulario para ingresar nuevo posteo de noticias
@login_required
def nueva_publicacion(request):
    if request.method == "POST":

        data_posteo = Nueva_noticia(request.POST,request.FILES)
        print(data_posteo)
        if data_posteo.is_valid():
            datos=data_posteo.cleaned_data
            #chequeo de cómo llega la información boolean desde el form
            print(datos["publicado"])
            posteo = Noticia(seccion=datos['seccion'] ,
                            titulo = datos['titulo'],
                            bajada = datos['bajada'],
                            cuerpo = datos['cuerpo'],
                            fecha = datetime.now(),
                            img = datos['img'],
                            nombre_user = datos['nombre_user'],
                            id_user = datos['id_user'],
                            publicado = datos['publicado'],
                            home = datos['home'])
            posteo.save() 
            return render(request, "index.html",dicc(request))
        else:
            print("data posteo no es valido")
    return render(request, "5nueva_publicacion.html",dicc(request)) 


#Búsqueda
@login_required
def resultados(request):
        avatares = Avatar.objects.filter(user=request.user.id)
        if request.GET['texto']:
            texto = request.GET['texto']
            # Búsqueda por Título y contenido de la noticia
            noticias = Noticia.objects.filter(bajada__icontains = texto) or Noticia.objects.filter(titulo__icontains = texto) or Noticia.objects.filter(cuerpo__icontains = texto)
            if avatares.exists():
                return render(request, "6resultados.html",{"noticias":noticias[::-1], "url":avatares[0].imagen.url})
            else:
                return render (request,"6resultados.html",{"noticias":noticias[::-1]})
        else:
            if avatares.exists():
                return render(request, "6resultados.html",{"url":avatares[0].imagen.url})
            else:
                return render (request,"6resultados.html")

#Lectura de noticias mediante link en título
def lectura(request,id):
    noticia_lectura = Noticia.objects.filter(id__exact = id)
    avatares = Avatar.objects.filter(user=request.user.id)
    data = dicc(request)
    data.update({"noticia_lectura":noticia_lectura})
    return render(request, "7lectura.html",data)

 
#Borrar publicaciones
@login_required
def borrar_publicacion(request,id_noticia):
    noticia_para_borrar = Noticia.objects.get(id=id_noticia)
    noticia_para_borrar.img.delete(False)
    noticia_para_borrar.delete()
    return render(request, "index.html",dicc(request))



#Editar publicaciones
#@login_required
def editar_publicacion(request,id_noticia):
    noticia_para_editar = Noticia.objects.get(id=id_noticia)
    if request.method == "POST":
        formulario_publicacion = Nueva_noticia(request.POST,request.FILES)
        if formulario_publicacion.is_valid():
            datos = formulario_publicacion.cleaned_data
            noticia_para_editar.seccion=datos['seccion']
            noticia_para_editar.titulo = datos['titulo']
            noticia_para_editar.bajada = datos['bajada']
            noticia_para_editar.cuerpo = datos['cuerpo']
            noticia_para_editar.fecha = datetime.now()
            noticia_para_editar.img.delete(False)
            noticia_para_editar.img = datos['img']
            noticia_para_editar.nombre_user = datos['nombre_user']
            noticia_para_editar.id_user = datos['id_user']
            noticia_para_editar.publicado = datos['publicado']
            noticia_para_editar.home = datos['home']
            noticia_para_editar.save()
            render(request, "index.html",dicc(request))
    else:
        formulario_publicacion = Nueva_noticia(initial={'seccion':noticia_para_editar.seccion,'titulo':noticia_para_editar.titulo,'bajada':noticia_para_editar.bajada,'cuerpo':noticia_para_editar.cuerpo,'fecha':datetime.now(),'img':noticia_para_editar.img,'nombre_user':noticia_para_editar.nombre_user,'id_user':noticia_para_editar.id_user,'publicado':noticia_para_editar.publicado,'home': noticia_para_editar.home})
    data = dicc(request)
    data.update({"formulario_publicacion":formulario_publicacion ,"noticia_para_editar":noticia_para_editar})
    return render(request, "editar_publicacion.html",data) 





# Login con formulario de django
def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contra = form.cleaned_data.get('password')
            user=authenticate(username=usuario, password=contra)
            if user is not None:
                login(request, user)
                return render(request, "index.html", dicc(request))
            else:
                data=dicc(request)
                data.update({"mensaje":"Usuario Incorrecto",'form':form})  
                return render(request,"login.html",data)
        else:
            data=dicc(request)
            data.update({"mensaje":"Error",'form':form})  
            return render(request,"login.html",data) 
    
    form = AuthenticationForm()
    data=dicc(request)
    data.update({'form':form})  
    return render(request,"login.html",data)
    


#Alta de nuevxs usuarixs
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            form = AuthenticationForm()
            data=dicc(request)
            data.update({'mensaje':'Registro Exitoso','form':form})  
            return render(request,"index.html",data)
    else:
        form = UserCreationForm()
    data=dicc(request)
    data.update({"form":form,"mensaje":"Error en el registro"})
    return render (request, "registro.html",data)


# Editar el perfi: cambio mail y/o contraseña
@login_required
def editar_perfil(request):
    usuario=request.user
    if request.method == 'POST':
            miFormulario=User_Edit_Form(request.POST)
            if miFormulario.is_valid():
                informacion = miFormulario.cleaned_data
                usuario.email = informacion['email']
                password = informacion['password1']
                usuario.set_password(password)
                usuario.save()
                return inicio(request,{"mensaje":"Contraseña cambiada exitosamente, por favor vuela a loggearse"})
                
    else:
        miFormulario = User_Edit_Form ( initial = {'email':usuario.email} )
        
    data = dicc(request)
    data.update({"miFormulario":miFormulario,"usuario":usuario})
    return render(request,"editar_perfil.html",data)




# Cambio de imagen de perfil/avatar
@login_required
def cambiar_avatar(request):
    avatares = Avatar.objects.filter(user=request.user.id)
    if avatares.exists():
        perfil = Avatar(id=avatares[0].id,
                        user=avatares[0].user,
                        imagen=request.FILES['imagen'])
        perfil.save()
        return render(request, "index.html",dicc(request))
    else:
        perfil = Avatar(id=request.user.id,
                        user=request.user,
                        imagen=request.FILES['imagen'])
        perfil.save()
        return render(request, "index.html",dicc(request))

# Acerca De
def about(request):

desafio_final/portal/templates/1politica.html
{% extends "padre.html" %}

{% load static %}

{% block contenido %}

<!-- SECCION POLITICA -->

<div class="wrapper">
  <div id="hpage_cats">
    <!--<div class="sticky-top">-->
      <div class="text-bg-light p-3">
        <h1>Política</h1>
     </div>
    <!--</div>-->
    <div class="accordion accordion-flush" id="accordionFlushExample">
      <div class="accordion-item">
        {% for n in noticias %}
          {% if n.seccion == "politica" and n.publicado == True %}
            <h2 class="accordion-header" id="flush-headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOn{{n.id}}" aria-expanded="false" aria-controls="flush-collapseOn{{n.id}}">
              {{n.titulo}}
            </button>
            </h2>
            <div id="flush-collapseOn{{n.id}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
              <div class="accordion-body">
                <div>
                  <a href="{% url 'lectura' n.id %}">
                  <table>
                    <td><img src="/media/{{n.img}}" alt="imagen de {{n.titulo}}" height="50" width="90"></td>
                    <td>{{n.bajada}}</td>
                  </table>
                </div>
                <br>
                <button type="button" class="btn btn-success"> <i class="fa-solid fa-newspaper"></i> Ir a la publicación</button></a>
                  {% if request.user.is_authenticated %}
                    {% if user.id == n.id_user %}
                      <a href="{% url 'editar_publicacion' n.id %}"><button type="button" class="btn btn-primary"></i> Editar</button></a>
                      <a class="btn btn-danger" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Borrar</a>
                      <div class="collapse" id="collapseExample">
                        <div class="card card-body">
                          ¿Borrar definitivamente?<a href="{% url 'borrar_publicacion' n.id %}"><button type="button" class="btn btn-danger"><i class="fa-solid fa-square-minus"></i> Si</button></a>
                        </div>
                      </div>
                    {% endif %}
                  {% endif %}
                </div>
              </div>
          {% endif %} 
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

desafio_final/portal/templates/5nueva_publicacion.html
{% extends "padre.html" %}

{% load static %}

{% block contenido %}
<script>

function countChars(obj){
    document.getElementById("charNum").innerHTML = obj.value.length+' caracteres (max 140)';
}
function countCharsBajada(obj){
    document.getElementById("charNum2").innerHTML = obj.value.length+' caracteres (max 10 mil)';
}
function countCharsCuerpo(obj){
    document.getElementById("charNum3").innerHTML = obj.value.length+' caracteres (max 30 mil)';
}
</script>

<div class="wrapper">
    <div id="hpage_cats">
        
        <h1>Ingresar nueva publicación</h1>
       
        <form action="nueva_publicacion" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        
        <!-- SELECTOR DE SECCION DE LA NOTICIA -->

            <label for="selector-seccion" class="form-label">Sección</label>
            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="seccion" id="selector-seccion" required>
                <option value="politica" selected>Política</option>
                <option value="economia">Economía</option>
                <option value="sociedad">Sociedad</option>
                <option value="deportes">Deportes</option>
            </select>
        <br>


        <!-- TITULO HASTA 140 CARACTERES -->

        <div class="mb-3">
            <label for="id_titulo" class="form-label">Título</label>
            <td><input type="text" class="form-control" size="140" id="id_titulo" placeholder="Título hasta 140 caractéres" name="titulo" onkeyup="countChars(this);" required></td>
            <td><h5 id="charNum">0 caractéres</h5> </td>
        </div>
        <br>


        <!-- TEXTAREA BAJADA HASTA 10 MIL CARACTERES-->

        <div class="mb-3">  
            <label for="Textarea_Bajada" class="form-label">Bajada</label>
            <textarea class="form-control" name="bajada" id="Textarea_Bajada" minlength="0" maxlength="10000" rows="3" placeholder="Hasta 10k caractéres" onkeyup="countCharsBajada(this);" required></textarea>
            <td><h5 id="charNum2">0 caractéres</h5> </td>
        </div>
        <br>

        
        <!-- TEXTAREA CUERPO HASTA 30 MIL CARACTERES-->

        <div class="mb-3">  
            <label for="Textarea_Cuerpo" class="form-label">Cuerpo</label>
            <textarea class="form-control" name="cuerpo" id="Textarea_Cuerpo" minlength="0" maxlength="30000" rows="3" placeholder="Hasta 30k caractéres" onkeyup="countCharsCuerpo(this);" required></textarea>
            <td><h5 id="charNum3">0 caractéres</h5> </td>
        </div>
        <br>

        <!-- Imagen del posteo -->

        <br>
        <div class="mb-3">
            <input class="form-control" type="file" placeholder="imagen" aria-label="default input example" name="img" id="id_img" required>
        
        </div>
        <br>
         <!-- NOMBRE Y MAIL DE USUARIXS -->
        
        <div class="mb-3">
            <label for="id_nombre_user" class="form-label">Nombre</label>
            <td><input type="text" class="form-control" size="140" id="id_nombre_user" value="{{user.username}}" name="nombre_user" readonly ></td>
            
        </div>
        <br>
        <div class="mb-3">
            <label for="id_id_user" class="form-label">ID de Usuario</label>
            <td><input type="number" class="form-control" size="140" id="id_id_user" value={{user.id}} name="id_user" readonly ></td>
            
        </div>


        <!-- SELECTORES BOOLEANOS de publicar y home -->

        <label for="selector-seccion" class="form-label">Publicado</label>
        <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="publicado" id="selector-seccion" required>
            <option value=1 selected>Si</option>
            <option value=0>No</option>
        </select>
        <label for="selector-seccion" class="form-label">Publicar en inicio</label>
        <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="home" id="selector-seccion" required>
            <option value=1>Si</option>
            <option value=0 selected>No</option>
        </select>
        <button type="submit" class="btn btn-primary">Publicar</button>
        </form>
    </div>
</div>




{% endblock %}

desafio_final/portal/templates/6resultados.html
{% extends "padre.html" %}

{% load static %}

{% block contenido %}

<div class="wrapper">
    <div id="hpage_cats">
      <div class="sticky-top">
        <div class="text-bg-light p-3">
          <h1>Resultados de la búsqueda ordenados desde el mas reciente</h1>
        </div>
      </div>
      <div class="accordion accordion-flush" id="accordionFlushExample">
        <div class="accordion-item">
          {% for n in noticias %}
            {% if n.publicado == True %}
              <h2 class="accordion-header" id="flush-headingOne">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOn{{n.id}}" aria-expanded="false" aria-controls="flush-collapseOn{{n.id}}">
                {% if n.seccion == "politica" %}
                    {% with secc="POLÍTICA" %}
                    <span class="badge bg-secondary">{{secc}}</span>  | ID: {{n.id}} | Título: {{n.titulo}}
                    {% endwith %}
                {% elif n.seccion == "economia" %}
                    {% with secc="ECONOMÍA" %}
                    <span class="badge bg-secondary">{{secc}}</span>  | ID: {{n.id}} | Título: {{n.titulo}}
                    {% endwith %}
                {% elif n.seccion == "sociedad" %}
                    {% with secc="SOCIEDAD" %}
                    <span class="badge bg-secondary">{{secc}}</span> | ID: {{n.id}} | Título: {{n.titulo}}
                    {% endwith %}
                {% elif n.seccion == "deportes" %}
                    {% with secc="DEPORTES" %}
                    <span class="badge bg-secondary">{{secc}}</span>  | ID: {{n.id}} | Título: {{n.titulo}}
                    {% endwith %}
                {% endif %}|
              </button>
              </h2>
              <div id="flush-collapseOn{{n.id}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">{{n.bajada}}
                  <br>
                    <a href="{% url 'lectura' n.id %}"><button type="button" class="btn btn-success"> <i class="fa-solid fa-newspaper"></i> Ir a la publicación</button></a>
                </div>
              </div>
            {% endif %} 
          {% endfor %}
        </div>
      </div>
    </div>
</div>



{% endblock %}

desafio_final/portal/templates/editar_publicacion.html
{% extends "padre.html" %}

{% load static %}

{% block contenido %}
<script>

function countChars(obj){
    document.getElementById("charNum").innerHTML = obj.value.length+' caracteres (max 140)';
}
function countCharsBajada(obj){
    document.getElementById("charNum2").innerHTML = obj.value.length+' caracteres (max 10 mil)';
}
function countCharsCuerpo(obj){
    document.getElementById("charNum3").innerHTML = obj.value.length+' caracteres (max 30 mil)';
}
</script>

<div class="wrapper">
    <div id="hpage_cats">
        <h1>Editar publicación</h1>
        <form action="{% url 'editar_publicacion' noticia_para_editar.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <select name="seccion" required>
                {% if noticia_para_editar.seccion == "politica" %}
                    <option value="politica" selected>Política</option>
                    <option value="economia">Economía</option>
                    <option value="sociedad">Sociedad</option>
                    <option value="deportes">Deportes</option>
                {% elif noticia_para_editar.seccion == "economia" %}
                    <option value="politica">Política</option>
                    <option value="economia" selected>Economía</option>
                    <option value="sociedad">Sociedad</option>
                    <option value="deportes">Deportes</option>
                {% elif noticia_para_editar.seccion == "sociedad" %}
                    <option value="politica">Política</option>
                    <option value="economia">Economía</option>
                    <option value="sociedad">Sociedad</option>
                    <option value="deportes">Deportes</option>
                {% elif noticia_para_editar.seccion == "deportes" %}
                    <option value="politica">Política</option>
                    <option value="economia">Economía</option>
                    <option value="sociedad">Sociedad</option>
                    <option value="deportes" selected>Deportes</option>
                {% endif %}
            </select>
            <br>
            <br>
            <h3>Título</h3>
            <td>
                <input type="text" class="form-control" size="140" id="exampleFormControlInput1" name="titulo" onkeyup="countChars(this);" value="{{ formulario_publicacion.titulo.value }}" required></td>
            <td>
                <h5 id="charNum">0 caractéres</h5>
            </td>
            <br>
            <h3>Bajada</h3>
            <br>
            <textarea class="form-control" name="bajada" id="exampleFormControlTextarea1" rows="6" cols="140" onkeyup="countCharsBajada(this);" required>
                {{ formulario_publicacion.bajada.value }}
            </textarea>
            <td>
                <h5 id="charNum2">0 caractéres</h5>
            </td>
            <br>
            <br>
            <h3>Cuerpo de la noticia</h3>
                <textarea class="form-control" name="cuerpo" id="exampleFormControlTextarea1" rows="6" cols="140" onkeyup="countCharsCuerpo(this);" required>
                    {{ formulario_publicacion.cuerpo.value }}
                </textarea>
            <td>
                <h5 id="charNum3">0 caractéres</h5>
            </td>
            <br>
            <br>
            <br>
            <div class="mb-3">
                <input class="form-control" type="file" placeholder="imagen" aria-label="default input example" name="img" id="id_img" required>
            </div>
            <br>     
            <!-- Nombre y ID de usuarix -->
            <div class="mb-3">
                <label for="id_nombre_user" class="form-label">Nombre</label>
                <td>
                    <input type="text" class="form-control" size="140" id="id_nombre_user" value="{{user.username}}" name="nombre_user" readonly >
                </td>
            </div>
            <br>
            <div class="mb-3">
                <label for="id_id_user" class="form-label">ID de Usuario</label>
                <td>
                    <input type="number" class="form-control" size="140" id="id_id_user" value={{user.id}} name="id_user" readonly >
                </td>
            </div>
            <br>
            <label for="selector-seccion" class="form-label">Publicado</label>
            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="publicado" id="selector-seccion" required>
                <option value=1 selected>Si</option>
                <option value=0>No</option>
            </select>
            <label for="selector-seccion" class="form-label">Publicar en inicio</label>
            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="home" id="selector-seccion" required>
                <option value=1 selected>Si</option>
                <option value=0>No</option>
            </select>           
            <input type="submit" value="Enviar">
            <a href="{% url 'inicio' %}"><input type="button" value="Cancelar"></a>
        </form>
    </div>
</div>

{% endblock %}